# Generated by Django 5.1.4 on 2024-12-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=20)),
                ('Sdesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('Tid', models.IntegerField(primary_key=True, serialize=False)),
                ('Sid', models.IntegerField()),
                ('Tname', models.CharField(max_length=20)),
                ('Tdesc', models.TextField()),
            ],
        ),
    ]
